// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: remote_exec.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommandRemoteExecClient is the client API for CommandRemoteExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandRemoteExecClient interface {
	CmdRemoteExec(ctx context.Context, in *CmdRequest, opts ...grpc.CallOption) (*CmdResponse, error)
}

type commandRemoteExecClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandRemoteExecClient(cc grpc.ClientConnInterface) CommandRemoteExecClient {
	return &commandRemoteExecClient{cc}
}

func (c *commandRemoteExecClient) CmdRemoteExec(ctx context.Context, in *CmdRequest, opts ...grpc.CallOption) (*CmdResponse, error) {
	out := new(CmdResponse)
	err := c.cc.Invoke(ctx, "/proto.CommandRemoteExec/cmdRemoteExec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandRemoteExecServer is the server API for CommandRemoteExec service.
// All implementations must embed UnimplementedCommandRemoteExecServer
// for forward compatibility
type CommandRemoteExecServer interface {
	CmdRemoteExec(context.Context, *CmdRequest) (*CmdResponse, error)
	mustEmbedUnimplementedCommandRemoteExecServer()
}

// UnimplementedCommandRemoteExecServer must be embedded to have forward compatible implementations.
type UnimplementedCommandRemoteExecServer struct {
}

func (UnimplementedCommandRemoteExecServer) CmdRemoteExec(context.Context, *CmdRequest) (*CmdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CmdRemoteExec not implemented")
}
func (UnimplementedCommandRemoteExecServer) mustEmbedUnimplementedCommandRemoteExecServer() {}

// UnsafeCommandRemoteExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandRemoteExecServer will
// result in compilation errors.
type UnsafeCommandRemoteExecServer interface {
	mustEmbedUnimplementedCommandRemoteExecServer()
}

func RegisterCommandRemoteExecServer(s grpc.ServiceRegistrar, srv CommandRemoteExecServer) {
	s.RegisterService(&CommandRemoteExec_ServiceDesc, srv)
}

func _CommandRemoteExec_CmdRemoteExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandRemoteExecServer).CmdRemoteExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandRemoteExec/cmdRemoteExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandRemoteExecServer).CmdRemoteExec(ctx, req.(*CmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandRemoteExec_ServiceDesc is the grpc.ServiceDesc for CommandRemoteExec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandRemoteExec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CommandRemoteExec",
	HandlerType: (*CommandRemoteExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "cmdRemoteExec",
			Handler:    _CommandRemoteExec_CmdRemoteExec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote_exec.proto",
}
