premier_test:premier_time_operations/premier.c
	$(CC) $< -o premier_time_operations/premier -lm
	chmod +x premier_time_operations/premier
	$(MAKE) --directory=premier_time_operations -f Makefile

clean:
	rm -f premier_time_operations/list*.txt 